### ISSUE TITLE
Volume bumps

### ISSUE THREAD

**Issue by erik-zarko** [MatthewCash/google-meet-volume-control#1]
When on fairly low levels, I could notice some volume bumps for less than a second and then returns to the actual volume selected.

**Comment by juliostorino** [comment]
I have the same issue !

**Comment by MatthewCash** [comment]
I haven't noticed any volume issues like this in testing and I worry this will be difficult to track down. Could you give some more information about the circumstances where it happens, are there a lot of people in the meet? Does it happen for every speaker or just a few? Does it only happen to people that just joined, and anything else that might help me reproduce it?

The method I use to set the tab volume is less than ideal, it sets the volume of all audio and video elements in a loop. This happens ever 100ms which might explain why the the volume bumps are short, but I don't see a reason for the volume to suddenly increase.
 
I would prefer to use something like a `gainNode` to control the volume of the entire tab at once, but the only way I have found to get audio into the gainNode is to get a stream using `chrome.tabCapture.capture` which would require user interaction each time, something that I want to avoid.

**Comment by jcstorino** [comment]
Hello! Here is some information that I could observe...

- No matter how many people in the room, when lowering the volume the audio bump's for a fraction second some times.
- Whatever speaker is are using (phone or notebook) the problem occurs.
- The problem occurs only for my audio, the participants don't even know that the volume has been reduced.

I'm trying to do some tests with the source of the extension, something tells me that it's a problem with the loop time that the adjustment is performed on the sound.

**Comment by jcstorino** [comment]
News...

I downloaded the extension source and did a direct installation, changing the update time from 100 to 10 msecs.
My first impression is that the audio bump's is less noticeable (almost nothing), very rarely I notice any noise.

**Comment by MatthewCash** [comment]
This suggests that something is either resetting the volume or the `audio` elements are being replaced, maybe I could try using a `MutationObserver` to detect changes, but I would want to know what is causing it first.

I have yet to reproduce this myself by creating a simple meet with 2 people, is there a way you know of to consistently trigger the volume bumps so that I can take a closer look at what is happening?

**Comment by jcstorino** [comment]
Hello!

A important couple informations ...

- It seems that it only occurs in the macos
- When using the google chrome meeting extension

<img width="1315" alt="image" src="https://github.com/MatthewCash/google-meet-volume-control/assets/19559870/d6d55046-c8c5-4cbc-aa68-d47a4b5bb296">

**Comment by MatthewCash** [comment]
I'm not going to be able to test with MacOS, but I am noticing something similar when the person speaking either mutes/unmutes or toggles their camera. I'll take a look at what is causing it and hopefully the fix will solve the whole issue.

**Comment by MatthewCash** [comment]
I added a listener to fix the volume anytime an audio node has its volumes changed. This appears to eliminate most of the volume bumps for me, but there are still some that are very short. This is probably the best I can for now do unless I can think of a better method.

When you get a chance, can you test the latest commit either by either building manually or loading the file I attached here?

[meet-volume-control.zip](https://github.com/MatthewCash/google-meet-volume-control/files/11854246/meet-volume-control.zip)

**Comment by jcstorino** [comment]
Hi !

I did the installation now and I will use it a lot on day, I will report the result soon !

Thank you.

**Comment by jcstorino** [comment]
Hello @MatthewCash 

I've been using the new extension for 2 days.. change volume in very noisy meetings.. and the audio bump reduced considerably!

I believe it was almost perfect! Your solution was great !
Thank's

**Comment by MatthewCash** [comment]
Version 1.2.0 contains this fix and should be available on the Chrome Web Store now.
