### ISSUE TITLE
Building on Windows

### ISSUE THREAD

**Issue by flaming910** [MatthewCash/google-meet-volume-control#3]
I'm trying to make a change so the volume control doesn't impact media because that messes with screen sharing audio. I can't seem to figure out how to build on windows 

This is my output:
```
$ npm run build:chrome

> meet-volume-control@1.2.0 build:chrome
> TARGET=chrome vite build

'TARGET' is not recognized as an internal or external command,
operable program or batch file.
```

Any idea how to make it work?

**Comment by MatthewCash** [comment]
The Windows command prompt does not accept environment variables in the same way that a posix shell does. I have never built the extension on Windows, so I had not encountered this.

I pushed a fix to wrap the commands with `cross-env`. Pull the changes, reinstall dependencies with `npm install`, and try to run the build command again. Let me know if it still doesn't work.
